apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-postgresql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/harbor/postgresql"
