apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-postgresql-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
