apiVersion: v1
kind: Service
metadata:
  name: harbor-postgresql
  namespace: harbor
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: harbor
spec:
  ports:
    - port: 5432
  selector:
    release: harbor
    app: harbor
    component: postgresql
