apiVersion: v1
kind: ConfigMap
metadata:
  name: "harbor-jobservice"
  namespace: harbor
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
data:
  config.yml: |+
    protocol: "http"
    port: 8080
    worker_pool:
      workers: 10
      backend: "redis"
      redis_pool:
        redis_url: "redis://harbor-redis:6379/1"
        namespace: "harbor_job_service_namespace"
        idle_timeout_second: 3600
    job_loggers:
      - name: "FILE"
        level: INFO
        settings:
          base_dir: "/var/log/jobs"
        sweeper:
          duration: 14
          settings:
            work_dir: "/var/log/jobs"
    metric:
      enabled: false
      path: /metrics
      port: 8001
    loggers:
      - name: "STD_OUTPUT"
        level: INFO
    reaper:
      max_update_hours: 24
      max_dangling_hours: 168
