apiVersion: v1
kind: Secret
metadata:
  name: "harbor-jobservice"
  namespace: harbor
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  secretKey: ""
  REGISTRY_PASSWD: ""
  CORE_SECRET: ""
