apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    app: keycloak
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/keycloak"
