apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: unbe1iev-sso
spec:
  serviceName: "mariadb"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.2.4
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name: MYSQL_DATABASE
          value: keycloak
        - name: MYSQL_USER
          value: keycloak
        - name: MYSQL_PASSWORD
          value: ""
        volumeMounts:
        - name: mariadb-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-pvc
        persistentVolumeClaim:
          claimName: mariadb-data
