apiVersion: v1
kind: PersistentVolume
metadata:
  name: unbe1iev-creator-db-pv
  labels:
    app: creator-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/unbe1iev-dev/creator-db
