apiVersion: v1
kind: Secret
metadata:
  name: harbor-core
  namespace: harbor
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  secretKey: ""
  CSRF_KEY: ""
  HARBOR_ADMIN_PASSWORD: ""
  POSTGRESQL_PASSWORD: ""
  REGISTRY_PASSWD: ""
  REGISTRY_HTPASSWD: ""
  JOBSERVICE_SECRET: ""
