apiVersion: v1
kind: Secret
metadata:
  name: "harbor-registry"
  namespace: harbor
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_REDIS_PASSWORD: ""
  REGISTRY_HTTP_SECRET: ""
  CORE_SECRET: ""
  JOBSERVICE_SECRET: ""
  REGISTRY_HTPASSWD: ""
  REDIS_URL: ""
