apiVersion: v1
kind: Service
metadata:
  name: "harbor-registry"
  namespace: harbor
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
spec:
  ports:
    - name: http-registry
      port: 5000
    - name: http-controller
      port: 8080
  selector:
    release: harbor
    app: "harbor"
    component: registry
