apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unbe1iev-creator
  namespace: unbe1iev-dev
spec:
  serviceName: "creator"
  replicas: 1
  selector:
    matchLabels:
      app: creator
  template:
    metadata:
      labels:
        app: creator
    spec:
      containers:
        - name: creator
          image: harbor.unbe1iev.com/unbe1iev-dev/creator:1.0.0
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: unbe1iev-creator-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: "creator"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unbe1iev-creator-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KEYCLOAK_CONFIG_URL
              value: "https://sso.unbe1iev.com"
            - name: KEYCLOAK_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unbe1iev-creator-secret
                  key: KEYCLOAK_CONFIG_PASSWORD
            - name: CREATOR_BACKEND_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: unbe1iev-creator-secret
                  key: CREATOR_BACKEND_CLIENT_SECRET
            - name: SECURITY_TRUSTED_ISSUERS
              value: "https://sso.unbe1iev.com/realms/unbe1iev"
      imagePullSecrets:
        - name: unbe1iev-docker-login
