apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-cosign-pv
  labels:
    type: harbor-cosign
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "harbor"
    meta.helm.sh/release-namespace: "harbor"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/harbor/cosign
