apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-cosign-pvc
  namespace: harbor
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "harbor"
    meta.helm.sh/release-namespace: "harbor"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: harbor-cosign
